version: '3.0'

services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=fc_healthcare
      - POSTGRES_USER=fc_healthcare_user
      - POSTGRES_PASSWORD=@Pass1234567890
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always

volumes:
  postgres_data:
  redis_data: